In [10]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('diabetes.csv')

In [13]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

USING KERAS TUNER TO GET THE BEST OPTIMIZER AMONG 4 OPTIONS

In [14]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [15]:
X  = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation= 'sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [20]:
model.fit(X_train, y_train, batch_size=32, epochs=100, verbose=1, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - accuracy: 0.5456 - loss: 9.3834 - val_accuracy: 0.4481 - val_loss: 6.4838
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5163 - loss: 3.5171 - val_accuracy: 0.5909 - val_loss: 2.0884
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5554 - loss: 2.1396 - val_accuracy: 0.5584 - val_loss: 1.5809
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5456 - loss: 1.3937 - val_accuracy: 0.6558 - val_loss: 1.1871
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6124 - loss: 1.1518 - val_accuracy: 0.6299 - val_loss: 1.0718
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6026 - loss: 0.9673 - val_accuracy: 0.6104 - val_loss: 0.9336
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6059 - loss: 0.9087 - val_accuracy: 0.6429 - val_loss: 0.8487
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6091 - loss: 0.8426 - val_accuracy: 0.6753 - val_loss: 0.8000
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6254 - loss: 0.8169 - val_accuracy: 0.6558 - val_loss: 0.8071
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.7675 - val_accuracy: 0.5909 - val_loss: 0.9335
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.8078 - val_accuracy: 0.6883 - val_loss: 0.7704
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.7569 - val_accuracy: 0.6494 - val_loss: 0.7979
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.7402 - val_accuracy: 0.6494 - val_loss: 0.7511
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6450 - loss: 0.7634 - val_accuracy: 0.6818 - val_loss: 0.7511
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6368 - loss: 0.7252 - val_accuracy: 0.6494 - val_loss: 0.7289
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6913 - val_accuracy: 0.6623 - val_loss: 0.7293
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6775 - loss: 0.6715 - val_accuracy: 0.6623 - val_loss: 0.7277
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6676 - val_accuracy: 0.6494 - val_loss: 0.8222
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6612 - loss: 0.6937 - val_accuracy: 0.6688 - val_loss: 0.7202
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.6495 - val_accuracy: 0.6688 - val_loss: 0.8541
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.6704 - val_accuracy: 0.6883 - val_loss: 0.7015
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.6291 - val_accuracy: 0.6558 - val_loss: 0.7002
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.6440 - val_accuracy: 0.6948 - val_loss: 0.7227
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.6673 - val_accuracy: 0.6364 - val_loss: 0.7123
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.6626 - val_accuracy: 0.6558 - val_loss: 0.7500
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6481 - val_accuracy: 0.7078 - val_loss: 0.7225
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6151 - val_accuracy: 0.6623 - val_loss: 0.6828
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6255 - val_accuracy: 0.6948 - val_loss: 0.6963
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5872 - val_accuracy: 0.6818 - val_loss: 0.6877
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5964 - val_accuracy: 0.6818 - val_loss: 0.6751
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.5893 - val_accuracy: 0.6688 - val_loss: 0.6518
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5818 - val_accuracy: 0.6558 - val_loss: 0.7485
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.6084 - val_accuracy: 0.6494 - val_loss: 0.6951
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5731 - val_accuracy: 0.6753 - val_loss: 0.6588
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5738 - val_accuracy: 0.6623 - val_loss: 0.7169
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5934 - val_accuracy: 0.7013 - val_loss: 0.7322
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5933 - val_accuracy: 0.6494 - val_loss: 0.6489
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5540 - val_accuracy: 0.6494 - val_loss: 0.6780
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.5926 - val_accuracy: 0.6429 - val_loss: 0.7228
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5599 - val_accuracy: 0.6688 - val_loss: 0.6548
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5479 - val_accuracy: 0.6364 - val_loss: 0.6736
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5394 - val_accuracy: 0.6883 - val_loss: 0.6841
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6694 - loss: 0.6051 - val_accuracy: 0.6688 - val_loss: 0.9538
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.6451 - val_accuracy: 0.6558 - val_loss: 0.6691
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5396 - val_accuracy: 0.6818 - val_loss: 0.6552
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5373 - val_accuracy: 0.7013 - val_loss: 0.6407
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5297 - val_accuracy: 0.7078 - val_loss: 0.6421
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7329 - loss: 0.5226 - val_accuracy: 0.6753 - val_loss: 0.6411
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5433 - val_accuracy: 0.6558 - val_loss: 0.6974
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5509 - val_accuracy: 0.6948 - val_loss: 0.6396
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5521 - val_accuracy: 0.6948 - val_loss: 0.6691
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7427 - loss: 0.5266 - val_accuracy: 0.7013 - val_loss: 0.6472
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7036 - loss: 0.5683 - val_accuracy: 0.6299 - val_loss: 0.7347
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7313 - loss: 0.5525 - val_accuracy: 0.6883 - val_loss: 0.6873
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7313 - loss: 0.5369 - val_accuracy: 0.7013 - val_loss: 0.6753
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7199 - loss: 0.5470 - val_accuracy: 0.6753 - val_loss: 0.6644
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7427 - loss: 0.5293 - val_accuracy: 0.7013 - val_loss: 0.6644
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7345 - loss: 0.5188 - val_accuracy: 0.7078 - val_loss: 0.6519
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7020 - loss: 0.5641 - val_accuracy: 0.7013 - val_loss: 0.6772
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7199 - loss: 0.6079 - val_accuracy: 0.7078 - val_loss: 0.6471
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5245 - val_accuracy: 0.6948 - val_loss: 0.6737
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5228 - val_accuracy: 0.6883 - val_loss: 0.6521
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5223 - val_accuracy: 0.6818 - val_loss: 0.6435
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5258 - val_accuracy: 0.7403 - val_loss: 0.6499
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5180 - val_accuracy: 0.7208 - val_loss: 0.6390
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5323 - val_accuracy: 0.6948 - val_loss: 0.6320
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5407 - val_accuracy: 0.7143 - val_loss: 0.6361
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5477 - val_accuracy: 0.7013 - val_loss: 0.6368
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5530 - val_accuracy: 0.6169 - val_loss: 0.7855
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5903 - val_accuracy: 0.6818 - val_loss: 0.8791
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.6290 - val_accuracy: 0.7078 - val_loss: 0.6576
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7508 - loss: 0.5195 - val_accuracy: 0.7143 - val_loss: 0.6422
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5332 - val_accuracy: 0.6883 - val_loss: 0.6255
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5103 - val_accuracy: 0.7143 - val_loss: 0.6372
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5064 - val_accuracy: 0.7078 - val_loss: 0.6328
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5127 - val_accuracy: 0.7273 - val_loss: 0.7187
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5405 - val_accuracy: 0.6818 - val_loss: 0.6724
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7378 - loss: 0.5149 - val_accuracy: 0.7208 - val_loss: 0.6338
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5251 - val_accuracy: 0.7208 - val_loss: 0.6387
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.5016 - val_accuracy: 0.6623 - val_loss: 0.6439
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5083 - val_accuracy: 0.7338 - val_loss: 0.6430
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5187 - val_accuracy: 0.6558 - val_loss: 0.6488
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5227 - val_accuracy: 0.5779 - val_loss: 0.7706
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5716 - val_accuracy: 0.7208 - val_loss: 0.6437
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5045 - val_accuracy: 0.7013 - val_loss: 0.6436
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5040 - val_accuracy: 0.7468 - val_loss: 0.6602
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4947 - val_accuracy: 0.7143 - val_loss: 0.6626
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5242 - val_accuracy: 0.7468 - val_loss: 0.6427
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5024 - val_accuracy: 0.7208 - val_loss: 0.6534
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5142 - val_accuracy: 0.6948 - val_loss: 0.6864
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5209 - val_accuracy: 0.6948 - val_loss: 0.6211
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4957 - val_accuracy: 0.6753 - val_loss: 0.6411
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5009 - val_accuracy: 0.7273 - val_loss: 0.6186
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.5072 - val_accuracy: 0.6688 - val_loss: 0.6459
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5054 - val_accuracy: 0.7143 - val_loss: 0.7067
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5566 - val_accuracy: 0.7403 - val_loss: 0.6490
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4913 - val_accuracy: 0.7013 - val_loss: 0.6261
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.4956 - val_accuracy: 0.7273 - val_loss: 0.6631
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5308 - val_accuracy: 0.6883 - val_loss: 0.6519
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4945 - val_accuracy: 0.7208 - val_loss: 0.6405

In [5]:
!pip install keras_tuner

Collecting keras_tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras_tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras_tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras_tuner) (2.32.4)
Collecting kt-legacy (from keras_tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras_tuner) (1.82.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras_tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras_tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras_tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras_tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras_tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras_tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras_tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras_tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras_tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras_tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 5.1 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras_tuner
Successfully installed keras_tuner-1.4.8 kt-legacy-1.0.5

In [6]:
import keras_tuner as kt

In [24]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim = 8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer = hp.Choice('optimizer',values =  ['adam', 'sgd', 'rmsprop', 'adadelta']), loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model

In [25]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
tuner.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

In [35]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [34]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [36]:
model.fit(X_train, y_train, batch_size = 32, epochs = 100, initial_epoch = 5, validation_data = (X_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - accuracy: 0.6401 - loss: 1.0664 - val_accuracy: 0.6948 - val_loss: 0.9457
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6629 - loss: 0.8962 - val_accuracy: 0.5779 - val_loss: 0.9515
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.8604 - val_accuracy: 0.6688 - val_loss: 1.0943
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.8319 - val_accuracy: 0.6558 - val_loss: 0.9819
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.8619 - val_accuracy: 0.7273 - val_loss: 0.7583
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6661 - loss: 0.7726 - val_accuracy: 0.7273 - val_loss: 0.6985
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6596 - loss: 0.7540 - val_accuracy: 0.7013 - val_loss: 0.7196
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.8016 - val_accuracy: 0.7273 - val_loss: 0.6848
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.7683 - val_accuracy: 0.6558 - val_loss: 0.9225
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6612 - loss: 0.7329 - val_accuracy: 0.7273 - val_loss: 0.6680
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.7631 - val_accuracy: 0.7273 - val_loss: 0.6463
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6645 - loss: 0.7291 - val_accuracy: 0.6688 - val_loss: 0.9203
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6547 - loss: 0.7372 - val_accuracy: 0.5325 - val_loss: 0.8652
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6596 - loss: 0.7026 - val_accuracy: 0.7078 - val_loss: 0.6782
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.7468 - val_accuracy: 0.6558 - val_loss: 0.7656
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6678 - loss: 0.6716 - val_accuracy: 0.5844 - val_loss: 0.9289
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6824 - loss: 0.6933 - val_accuracy: 0.6948 - val_loss: 0.7303
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6726 - loss: 0.7062 - val_accuracy: 0.4351 - val_loss: 1.2247
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6596 - loss: 0.7341 - val_accuracy: 0.6818 - val_loss: 0.7639
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6873 - loss: 0.6648 - val_accuracy: 0.6429 - val_loss: 0.8408
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6547 - loss: 0.6869 - val_accuracy: 0.6558 - val_loss: 0.8029
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6645 - loss: 0.6830 - val_accuracy: 0.6818 - val_loss: 0.6745
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6743 - loss: 0.6897 - val_accuracy: 0.6688 - val_loss: 0.6749
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6629 - loss: 0.6691 - val_accuracy: 0.6883 - val_loss: 0.6570
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6792 - loss: 0.6731 - val_accuracy: 0.6623 - val_loss: 0.6983
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6743 - loss: 0.6612 - val_accuracy: 0.5584 - val_loss: 0.9194
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6987 - loss: 0.6650 - val_accuracy: 0.7143 - val_loss: 0.7513
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6184 - val_accuracy: 0.5584 - val_loss: 0.7809
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.6833 - val_accuracy: 0.6429 - val_loss: 0.7254
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.6404 - val_accuracy: 0.6688 - val_loss: 0.7541
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6619 - val_accuracy: 0.6883 - val_loss: 0.6421
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.6379 - val_accuracy: 0.6623 - val_loss: 0.7425
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6857 - loss: 0.6613 - val_accuracy: 0.5974 - val_loss: 0.7080
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.6752 - val_accuracy: 0.7338 - val_loss: 0.6446
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.6576 - val_accuracy: 0.6948 - val_loss: 0.6338
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.6463 - val_accuracy: 0.6429 - val_loss: 0.9899
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7068 - loss: 0.6195 - val_accuracy: 0.6623 - val_loss: 0.6612
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6840 - loss: 0.6522 - val_accuracy: 0.7208 - val_loss: 0.6421
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6971 - loss: 0.6247 - val_accuracy: 0.5584 - val_loss: 0.9454
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6922 - loss: 0.6517 - val_accuracy: 0.6494 - val_loss: 1.0335
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6889 - loss: 0.6560 - val_accuracy: 0.7078 - val_loss: 0.6570
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7134 - loss: 0.6160 - val_accuracy: 0.6429 - val_loss: 1.3009
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.6507 - val_accuracy: 0.6494 - val_loss: 0.7129
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6954 - loss: 0.6698 - val_accuracy: 0.5000 - val_loss: 0.8907
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.6491 - val_accuracy: 0.7273 - val_loss: 0.6083
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7117 - loss: 0.6061 - val_accuracy: 0.6299 - val_loss: 0.6776
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6824 - loss: 0.6369 - val_accuracy: 0.6558 - val_loss: 0.7895
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6857 - loss: 0.6333 - val_accuracy: 0.6429 - val_loss: 0.6660
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5981 - val_accuracy: 0.7403 - val_loss: 0.6300
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6055 - val_accuracy: 0.6429 - val_loss: 1.0058
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6226 - val_accuracy: 0.6688 - val_loss: 1.1608
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.6250 - val_accuracy: 0.6948 - val_loss: 0.6942
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6954 - loss: 0.6419 - val_accuracy: 0.6818 - val_loss: 0.6735
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7085 - loss: 0.6176 - val_accuracy: 0.6364 - val_loss: 0.6830
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.6396 - val_accuracy: 0.7013 - val_loss: 0.6869
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.6217 - val_accuracy: 0.6818 - val_loss: 0.6416
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6313 - val_accuracy: 0.6494 - val_loss: 0.7629
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.6021 - val_accuracy: 0.7273 - val_loss: 0.7156
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 0.6129 - val_accuracy: 0.6753 - val_loss: 0.8401
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7036 - loss: 0.6443 - val_accuracy: 0.6948 - val_loss: 0.6550
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.5967 - val_accuracy: 0.7273 - val_loss: 0.6753
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.6153 - val_accuracy: 0.6818 - val_loss: 0.6415
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6028 - val_accuracy: 0.6688 - val_loss: 0.9940
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6258 - val_accuracy: 0.6883 - val_loss: 0.7701
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6906 - loss: 0.6292 - val_accuracy: 0.5779 - val_loss: 0.8873
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7199 - loss: 0.5692 - val_accuracy: 0.6104 - val_loss: 0.7373
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.5963 - val_accuracy: 0.7468 - val_loss: 0.6074
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.6015 - val_accuracy: 0.7013 - val_loss: 0.6840
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.6075 - val_accuracy: 0.7338 - val_loss: 0.6404
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.6201 - val_accuracy: 0.6623 - val_loss: 1.1237
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.6139 - val_accuracy: 0.7143 - val_loss: 0.6191
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6906 - loss: 0.5965 - val_accuracy: 0.7013 - val_loss: 0.6253
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.6137 - val_accuracy: 0.7273 - val_loss: 0.6145
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7182 - loss: 0.5932 - val_accuracy: 0.7273 - val_loss: 0.6107
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.5915 - val_accuracy: 0.6623 - val_loss: 0.8366
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5855 - val_accuracy: 0.6169 - val_loss: 0.7277
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6987 - loss: 0.6341 - val_accuracy: 0.6883 - val_loss: 0.6336
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.5705 - val_accuracy: 0.6948 - val_loss: 0.7219
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7068 - loss: 0.6158 - val_accuracy: 0.6883 - val_loss: 0.7553
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5477 - val_accuracy: 0.6429 - val_loss: 1.2500
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.6018 - val_accuracy: 0.5584 - val_loss: 0.8254
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7182 - loss: 0.5734 - val_accuracy: 0.7338 - val_loss: 0.6017
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7345 - loss: 0.5808 - val_accuracy: 0.6104 - val_loss: 0.7526
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.6220 - val_accuracy: 0.6688 - val_loss: 0.7678
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5880 - val_accuracy: 0.6623 - val_loss: 0.6502
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5801 - val_accuracy: 0.7078 - val_loss: 0.6396
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.6256 - val_accuracy: 0.7078 - val_loss: 0.6451
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7264 - loss: 0.5610 - val_accuracy: 0.7013 - val_loss: 0.6263
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7117 - loss: 0.5958 - val_accuracy: 0.6688 - val_loss: 0.6843
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7117 - loss: 0.5810 - val_accuracy: 0.6429 - val_loss: 1.2304
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7378 - loss: 0.5827 - val_accuracy: 0.6688 - val_loss: 0.6590
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7362 - loss: 0.5811 - val_accuracy: 0.7208 - val_loss: 0.6543
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6938 - loss: 0.6199 - val_accuracy: 0.6623 - val_loss: 0.7874
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7085 - loss: 0.5769 - val_accuracy: 0.7143 - val_loss: 0.6367
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7215 - loss: 0.5832 - val_accuracy: 0.6883 - val_loss: 0.7028

GETTING THE BEST U<BER OF UNITS IN THE FIRST LAYER

In [39]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', 8, 128, step = 8)
  model.add(Dense(units = units, activation = 'relu', input_dim = 8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer = 'rmsprop', loss =  'binary_crossentropy', metrics = ['accuracy'])
  return model

In [42]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'mydir')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [43]:
tuner.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6363636255264282

Best val_accuracy So Far: 0.701298713684082
Total elapsed time: 00h 00m 18s

In [44]:
tuner.get_best_hyperparameters()[0].values

{'units': 40}

In [45]:
model = tuner.get_best_models(num_models = 1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [46]:
model.fit(X_train,y_train, batch_size=32, epochs = 100, initial_epoch = 5, validation_data = (X_test, y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.6091 - loss: 0.9490 - val_accuracy: 0.6494 - val_loss: 0.9245
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.7974 - val_accuracy: 0.5390 - val_loss: 1.1890
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6156 - loss: 0.8424 - val_accuracy: 0.6688 - val_loss: 0.8797
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6515 - loss: 0.7762 - val_accuracy: 0.6883 - val_loss: 0.7881
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.7583 - val_accuracy: 0.6688 - val_loss: 1.0467
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.7465 - val_accuracy: 0.6558 - val_loss: 0.9144
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6287 - loss: 0.7709 - val_accuracy: 0.5779 - val_loss: 0.9504
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.7121 - val_accuracy: 0.5325 - val_loss: 1.0745
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.7164 - val_accuracy: 0.5909 - val_loss: 0.9838
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6881 - val_accuracy: 0.6299 - val_loss: 0.7276
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6482 - loss: 0.6879 - val_accuracy: 0.7143 - val_loss: 0.6684
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6906 - val_accuracy: 0.6494 - val_loss: 1.2458
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.6841 - val_accuracy: 0.5909 - val_loss: 0.7553
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.6393 - val_accuracy: 0.6169 - val_loss: 0.7503
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6678 - loss: 0.6635 - val_accuracy: 0.6883 - val_loss: 0.6835
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.6363 - val_accuracy: 0.7208 - val_loss: 0.6751
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6775 - loss: 0.6249 - val_accuracy: 0.6494 - val_loss: 1.1656
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6560 - val_accuracy: 0.6818 - val_loss: 0.6846
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6857 - loss: 0.6375 - val_accuracy: 0.6623 - val_loss: 0.8357
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6374 - val_accuracy: 0.6429 - val_loss: 0.8897
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6759 - loss: 0.6616 - val_accuracy: 0.6558 - val_loss: 0.6952
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5935 - val_accuracy: 0.6948 - val_loss: 0.8361
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.6319 - val_accuracy: 0.5844 - val_loss: 0.7678
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6987 - loss: 0.5947 - val_accuracy: 0.6039 - val_loss: 0.7977
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6824 - loss: 0.6464 - val_accuracy: 0.7013 - val_loss: 0.6152
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6938 - loss: 0.6201 - val_accuracy: 0.5974 - val_loss: 0.8645
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.6077 - val_accuracy: 0.6623 - val_loss: 0.7459
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.6007 - val_accuracy: 0.5455 - val_loss: 0.9109
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7036 - loss: 0.6272 - val_accuracy: 0.6494 - val_loss: 1.0172
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7362 - loss: 0.5992 - val_accuracy: 0.6429 - val_loss: 0.8268
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7150 - loss: 0.5819 - val_accuracy: 0.4610 - val_loss: 1.3814
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.6142 - val_accuracy: 0.6494 - val_loss: 1.0990
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.6056 - val_accuracy: 0.6429 - val_loss: 1.0726
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.6023 - val_accuracy: 0.6623 - val_loss: 1.1302
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.6152 - val_accuracy: 0.4870 - val_loss: 1.1745
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6954 - loss: 0.6393 - val_accuracy: 0.5390 - val_loss: 0.9454
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7117 - loss: 0.5875 - val_accuracy: 0.6494 - val_loss: 0.9030
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6906 - loss: 0.5950 - val_accuracy: 0.5000 - val_loss: 1.0257
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6954 - loss: 0.6162 - val_accuracy: 0.6104 - val_loss: 0.7403
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6922 - loss: 0.5855 - val_accuracy: 0.6104 - val_loss: 0.7299
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6840 - loss: 0.5923 - val_accuracy: 0.6104 - val_loss: 0.7653
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6824 - loss: 0.6383 - val_accuracy: 0.7273 - val_loss: 0.6267
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7182 - loss: 0.5868 - val_accuracy: 0.6623 - val_loss: 0.9902
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7182 - loss: 0.5873 - val_accuracy: 0.7013 - val_loss: 0.6295
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7003 - loss: 0.6211 - val_accuracy: 0.6948 - val_loss: 0.6785
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6808 - loss: 0.6097 - val_accuracy: 0.6558 - val_loss: 0.7303
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.5754 - val_accuracy: 0.6688 - val_loss: 0.7193
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.6009 - val_accuracy: 0.6948 - val_loss: 0.7108
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5783 - val_accuracy: 0.7273 - val_loss: 0.6309
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6054 - val_accuracy: 0.7143 - val_loss: 0.6908
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5596 - val_accuracy: 0.5779 - val_loss: 0.8325
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5709 - val_accuracy: 0.4481 - val_loss: 1.3880
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 0.6079 - val_accuracy: 0.6558 - val_loss: 1.0163
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5621 - val_accuracy: 0.6494 - val_loss: 0.9238
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.6000 - val_accuracy: 0.6558 - val_loss: 0.7150
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5657 - val_accuracy: 0.6948 - val_loss: 0.6655
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.5639 - val_accuracy: 0.7078 - val_loss: 0.6548
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5700 - val_accuracy: 0.5260 - val_loss: 1.1497
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.6069 - val_accuracy: 0.6429 - val_loss: 0.8346
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6857 - loss: 0.6075 - val_accuracy: 0.6494 - val_loss: 0.8354
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5844 - val_accuracy: 0.5714 - val_loss: 0.8558
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5896 - val_accuracy: 0.6494 - val_loss: 1.1482
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7248 - loss: 0.5772 - val_accuracy: 0.7013 - val_loss: 0.6381
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5832 - val_accuracy: 0.6753 - val_loss: 0.6846
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7036 - loss: 0.5690 - val_accuracy: 0.5260 - val_loss: 0.9507
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5651 - val_accuracy: 0.5779 - val_loss: 0.8764
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7101 - loss: 0.5673 - val_accuracy: 0.6623 - val_loss: 0.6851
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7182 - loss: 0.5713 - val_accuracy: 0.6104 - val_loss: 0.7942
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5952 - val_accuracy: 0.4675 - val_loss: 1.1240
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5975 - val_accuracy: 0.5260 - val_loss: 1.0675
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5710 - val_accuracy: 0.7143 - val_loss: 0.7022
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5475 - val_accuracy: 0.6558 - val_loss: 0.7426
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.5820 - val_accuracy: 0.6883 - val_loss: 0.6751
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5970 - val_accuracy: 0.6364 - val_loss: 0.7575
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5494 - val_accuracy: 0.6558 - val_loss: 1.2198
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6971 - loss: 0.6071 - val_accuracy: 0.6623 - val_loss: 0.7518
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5874 - val_accuracy: 0.6818 - val_loss: 0.6533
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5689 - val_accuracy: 0.7208 - val_loss: 0.6383
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7296 - loss: 0.5613 - val_accuracy: 0.6623 - val_loss: 1.2906
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5890 - val_accuracy: 0.5909 - val_loss: 0.8411
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5859 - val_accuracy: 0.6558 - val_loss: 1.1555
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 0.5820 - val_accuracy: 0.6169 - val_loss: 0.7518
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5723 - val_accuracy: 0.6623 - val_loss: 0.7897
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5959 - val_accuracy: 0.7208 - val_loss: 0.6778
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5814 - val_accuracy: 0.6558 - val_loss: 0.7157
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5462 - val_accuracy: 0.5519 - val_loss: 0.9521
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7068 - loss: 0.5722 - val_accuracy: 0.6623 - val_loss: 0.7005
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5593 - val_accuracy: 0.6299 - val_loss: 0.7154
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7166 - loss: 0.5719 - val_accuracy: 0.6494 - val_loss: 0.9961
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7052 - loss: 0.5780 - val_accuracy: 0.7208 - val_loss: 0.6849
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5725 - val_accuracy: 0.6169 - val_loss: 0.7318
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5670 - val_accuracy: 0.7208 - val_loss: 0.6542
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.5849 - val_accuracy: 0.5325 - val_loss: 1.1165
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5982 - val_accuracy: 0.5519 - val_loss: 0.9348
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5353 - val_accuracy: 0.6688 - val_loss: 0.7783

GETTING THE BEST NUKBER OF LAYERS

In [48]:
def build_model(hp):
  model  =Sequential()
  model.add(Dense(40, activation= 'relu', input_dim = 8));
  for i in range(hp.Int('num_layers', min_value = 1, max_value = 10)):
    model.add(Dense(40, activation = 'relu'))
  model.add(Dense(1, activation = 'sigmoid'))

  model.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model

In [54]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'mydir2')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [55]:
tuner.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.6883116960525513

Best val_accuracy So Far: 0.7207792401313782
Total elapsed time: 00h 00m 25s

In [56]:
tuner.get_best_hyperparameters()[0].values

# since the best number of layers is 1 we have already created this model, so no need to create it again

{'num_layers': 1}

FINDING BOTH THE NUMBER OF LAYERS AND THE NUMBER OF NEURONS IN EACH LAYER TOGETHER

In [64]:
def build_model(hp):
    model = Sequential()

    # Tune the number of layers using a loop counter
    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        if i == 0:
            model.add(Dense(
                units=hp.Int(f'units_{i}', min_value=8, max_value=128, step=8),
                activation=hp.Choice(f'activation_{i}', values=['relu', 'tanh', 'sigmoid']),
                input_dim=8
            ))
        else:
            model.add(Dense(
                units=hp.Int(f'units_{i}', min_value=8, max_value=128, step=8),
                activation=hp.Choice(f'activation_{i}', values=['relu', 'tanh', 'sigmoid'])
            ))

    model.add(Dense(1, activation='sigmoid'))

    model.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model


    # using f strings because we need to give unique names to each segment in the loop

In [65]:
tuner = kt.RandomSearch(build_model, objective = 'val_accuracy', max_trials = 5, directory = 'mydir3')

In [66]:
tuner.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 5 Complete [00h 00m 07s]
val_accuracy: 0.6623376607894897

Best val_accuracy So Far: 0.6948052048683167
Total elapsed time: 00h 00m 30s

In [67]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units_0': 128,
 'activation_0': 'sigmoid',
 'units_1': 48,
 'activation_1': 'relu',
 'units_2': 40,
 'activation_2': 'relu',
 'units_3': 16,
 'activation_3': 'tanh',
 'units_4': 8,
 'activation_4': 'relu',
 'units_5': 72,
 'activation_5': 'tanh',
 'units_6': 96,
 'activation_6': 'sigmoid',
 'units_7': 32,
 'activation_7': 'relu',
 'units_8': 112,
 'activation_8': 'sigmoid'}

In [69]:
best_model = tuner.get_best_models(num_models = 1)[0]
best_model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,281 (5.00 KB)

 Trainable params: 1,281 (5.00 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
# only one layer was used in the best model