In [45]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, MissingIndicator
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../titanic.csv', usecols=['Age', 'Fare', 'Survived'])

In [46]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [47]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
X_train.head()

      Age     Fare
331  45.5  28.5000
733  23.0  13.0000
382  32.0   7.9250
704  26.0   7.8542
813   6.0  31.2750

In [50]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [55]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train_trf, y_train)
y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)
X_train

      Age      Fare  Age_NA
331  45.5   28.5000   False
733  23.0   13.0000   False
382  32.0    7.9250   False
704  26.0    7.8542   False
813   6.0   31.2750   False
..    ...       ...     ...
106  21.0    7.6500   False
270   NaN   31.0000    True
860  41.0   14.1083   False
435  14.0  120.0000   False
102  21.0   77.2875   False

[712 rows x 3 columns]

In [56]:
mi = MissingIndicator()
X_train_mi = mi.fit_transform(X_train[['Age']])
X_test_mi = mi.transform(X_test[['Age']])

X_train['Age_NA'] = X_train_mi
X_test['Age_NA'] = X_test_mi

si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [58]:

clf2 = LogisticRegression()
clf2.fit(X_train_trf2, y_train) 
y_pred2 = clf2.predict(X_test_trf2)
accuracy_score(y_test, y_pred2)

0.6368715083798883

Another method using only the simple imputer class

In [59]:
si = SimpleImputer(add_indicator=True)
X_train_trf3 = si.fit_transform(X_train)
X_test_trf3 = si.transform(X_test)

from sklearn.linear_model import LogisticRegression
clf3 = LogisticRegression()
clf3.fit(X_train_trf3, y_train)
y_pred3 = clf3.predict(X_test_trf3)

accuracy_score(y_test, y_pred3)

0.6368715083798883